# Generated by Django 4.2.16 on 2024-11-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_title',
            field=models.CharField(default='Untitled Application', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_summary',
            field=models.TextField(default='No summary provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], max_length=20),
        ),
    ]
